services:

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - '3306:3306'
    expose:
      - 3306

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    expose:
      - 6379